font:
  size: 9.0
  normal:
    family: Terminus
    style: Regular

  bold:
    style: Bold

  italic:
    style: Regular

  bold_italic:
    style: Bold

window:
  padding:
    x: 8
    y: 8

cursor:
  style: Underline

colors:
  # Default colors
  primary:
    background: '0x181818'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x181818'
    cursor: '0xd8d8d8'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xdc9656'
    green:   '0x282828'
    yellow:  '0x383838'
    blue:    '0xb8b8b8'
    magenta: '0xe8e8e8'
    cyan:    '0xa16946'
    white:   '0xf8f8f8'

draw_bold_text_with_bright_colors: false

